beamline_control:
  sst_control:
    _target_: sst_gui.loaders.controlFromOphyd
    label: Endstation in Control
    prefix: sst_control
controllers:
  adr:
    _target_: sst_gui.loaders.modelFromOphyd
    label: Refrigerator
    prefix: adr
detectors:
  _default:
    _target_: sst_gui.loaders.scalarFromOphyd
  i0:
    label: Gold Mesh
    prefix: i0
  ref:
    label: Multimesh
    prefix: ref
  sc:
    label: Drain Current
    prefix: sc
energy:
  energy:
    _target_: sst_gui.loaders.energyModelFromOphyd
    label: Energy
    prefix: en
gatevalves:
  _default:
    _target_: sst_gui.loaders.modelFromOphyd
  gv26:
    label: Post Shutter Gate Valve
    prefix: gv26
  gv27:
    label: Upstream Gate Valve
    prefix: gv27
  gv28:
    label: Downstream Gate Valve
    prefix: gv28
manipulators:
  manipulator:
    _target_: sst_gui.loaders.manipulatorFromOphyd
    label: Sample Manipulator
    prefix: manipulator
  multimesh:
    _target_: sst_gui.loaders.manipulatorFromOphyd
    label: Multimesh Reference Ladder
    prefix: multimesh
mirrors:
  _default:
    _target_: sst_gui.loaders.modelFromOphyd
  mir1:
    label: SST 1 Mirror 1 fmb
    prefix: mir1
  mir3:
    label: SST 1 Mirror 3 fmb
    prefix: mir3
  mir4:
    label: SST 1 Mirror 4 fmb
    prefix: mir4
motors:
  Exit_Slit:
    label: Exit Slit of Mono Vertical Gap
    prefix: Exit_Slit
  _default:
    _target_: sst_gui.loaders.motorFromOphyd
  i0upAu:
    label: Gold Mesh Motor
    prefix: i0upAu
  tesz:
    label: TES Translation
    prefix: tesz
shutters:
  _default:
    _target_: sst_gui.loaders.gvFromOphyd
  psh1:
    label: Front-End Shutter
    prefix: psh1
    visible: false
  psh10:
    label: Upstream Photon Shutter
    prefix: psh10
    visible: true
  psh4:
    label: Hutch Photon Shutter
    prefix: psh4
  psh7:
    label: Downstream Photon Shutter
    prefix: psh7
signals:
  _default:
    _target_: sst_gui.loaders.pvFromOphyd
  ring_current:
    label: NSLS-II Ring Current
    prefix: ring_current
